"""LiveDNS tools (/v5/livedns)."""

from __future__ import annotations

from typing import Any

from fastmcp import Context, FastMCP

from gandi_mcp.errors import handle_client_error
from gandi_mcp.tools._common import assert_readwrite, get_client


def register_livedns_tools(mcp: FastMCP) -> None:
    """Register LiveDNS tools on the server."""

    # ── Read ────────────────────────────────────────────────────────────

    @mcp.tool(tags={"gandi", "livedns"})
    async def livedns_list_domains(ctx: Context) -> list[dict[str, Any]]:
        """List all domains managed by LiveDNS."""
        try:
            return await get_client(ctx).livedns_list_domains()
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(tags={"gandi", "livedns"})
    async def livedns_get_domain(ctx: Context, fqdn: str) -> dict[str, Any]:
        """Get LiveDNS zone metadata for a domain.

        Args:
            fqdn: Fully-qualified domain name.
        """
        try:
            return await get_client(ctx).livedns_get_domain(fqdn)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(tags={"gandi", "livedns"})
    async def livedns_list_nameservers(ctx: Context, fqdn: str) -> list[str]:
        """Get the LiveDNS nameservers assigned to a domain.

        Args:
            fqdn: Fully-qualified domain name.
        """
        try:
            return await get_client(ctx).livedns_list_nameservers(fqdn)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(tags={"gandi", "livedns"})
    async def livedns_list_rrtypes(ctx: Context) -> list[str]:
        """List DNS record types accepted by LiveDNS (A, AAAA, CNAME, MX, etc.)."""
        try:
            return await get_client(ctx).livedns_list_rrtypes()
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(tags={"gandi", "livedns"})
    async def livedns_list_records(
        ctx: Context,
        fqdn: str,
        name: str | None = None,
        rrset_type: str | None = None,
    ) -> list[dict[str, Any]]:
        """List records in a LiveDNS zone, optionally filtered.

        Args:
            fqdn: Fully-qualified domain name.
            name: Optional record name (e.g. "www", "@").
            rrset_type: Optional record type (e.g. "A", "TXT", "MX").
        """
        try:
            return await get_client(ctx).livedns_list_records(fqdn, name=name, rrset_type=rrset_type)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(tags={"gandi", "livedns"})
    async def livedns_list_dnssec_keys(ctx: Context, fqdn: str) -> list[dict[str, Any]]:
        """List DNSSEC keys generated by LiveDNS for a domain.

        Args:
            fqdn: Fully-qualified domain name.
        """
        try:
            return await get_client(ctx).livedns_list_keys(fqdn)
        except Exception as e:
            handle_client_error(e)

    # ── Write (non-purchasing) ──────────────────────────────────────────

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": False},
    )
    async def livedns_add_domain(ctx: Context, fqdn: str) -> dict[str, Any]:
        """Add a domain to LiveDNS (enables zone management).

        Args:
            fqdn: Fully-qualified domain name (must be registered in this account).
        """
        try:
            assert_readwrite(ctx, "add LiveDNS domain")
            return await get_client(ctx).livedns_add_domain(fqdn)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": False},
    )
    async def livedns_update_domain(
        ctx: Context,
        fqdn: str,
        automatic_snapshots: bool | None = None,
    ) -> dict[str, Any]:
        """Update LiveDNS zone settings.

        Args:
            fqdn: Fully-qualified domain name.
            automatic_snapshots: Enable/disable auto snapshot on edits.
        """
        try:
            assert_readwrite(ctx, "update LiveDNS domain settings")
            data: dict[str, Any] = {}
            if automatic_snapshots is not None:
                data["automatic_snapshots"] = automatic_snapshots
            return await get_client(ctx).livedns_patch_domain(fqdn, data)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": False},
    )
    async def livedns_create_record(
        ctx: Context,
        fqdn: str,
        name: str,
        rrset_type: str,
        values: list[str],
        ttl: int | None = None,
    ) -> dict[str, Any]:
        """Create a single DNS record.

        Args:
            fqdn: Fully-qualified domain name.
            name: Record name (e.g. "www", "@", "_acme-challenge").
            rrset_type: Record type (A, AAAA, CNAME, MX, TXT, SRV, CAA, etc.).
            values: Record values — for MX include priority ("10 mail.example.com").
                TXT values are passed as raw strings (the API does not require
                zonefile-style embedded quotes).
            ttl: Time-to-live in seconds (300-2592000). Zone default if omitted.
        """
        try:
            assert_readwrite(ctx, "create DNS record")
            return await get_client(ctx).livedns_create_record(fqdn, name, rrset_type, values, ttl=ttl)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": False},
    )
    async def livedns_replace_record(
        ctx: Context,
        fqdn: str,
        name: str,
        rrset_type: str,
        values: list[str],
        ttl: int | None = None,
    ) -> dict[str, Any]:
        """Replace a specific (name, type) record set entirely.

        Args:
            fqdn: Fully-qualified domain name.
            name: Record name.
            rrset_type: Record type.
            values: New values (fully replaces existing values).
            ttl: New TTL. Zone default if omitted.
        """
        try:
            assert_readwrite(ctx, "replace DNS record")
            return await get_client(ctx).livedns_replace_record(fqdn, name, rrset_type, values, ttl=ttl)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": True},
    )
    async def livedns_replace_zone(
        ctx: Context,
        fqdn: str,
        items: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Replace ALL records in a zone (destructive bulk operation).

        Args:
            fqdn: Fully-qualified domain name.
            items: Full list of records — each item must have ``rrset_name``,
                ``rrset_type``, ``rrset_values`` and optionally ``rrset_ttl``.
        """
        try:
            assert_readwrite(ctx, "replace entire zone")
            return await get_client(ctx).livedns_replace_zone(fqdn, items)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": True},
    )
    async def livedns_delete_record(
        ctx: Context,
        fqdn: str,
        name: str,
        rrset_type: str,
    ) -> dict[str, Any]:
        """Delete a specific (name, type) record set.

        Args:
            fqdn: Fully-qualified domain name.
            name: Record name.
            rrset_type: Record type.
        """
        try:
            assert_readwrite(ctx, "delete DNS record")
            return await get_client(ctx).livedns_delete_record(fqdn, name, rrset_type)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": True},
    )
    async def livedns_delete_all_records(ctx: Context, fqdn: str) -> dict[str, Any]:
        """Delete ALL records in a zone (highly destructive — snapshot first).

        Args:
            fqdn: Fully-qualified domain name.
        """
        try:
            assert_readwrite(ctx, "delete all zone records")
            return await get_client(ctx).livedns_delete_all_records(fqdn)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": False},
    )
    async def livedns_create_dnssec_key(
        ctx: Context,
        fqdn: str,
        flags: int = 257,
    ) -> dict[str, Any]:
        """Create a LiveDNS DNSSEC key.

        Args:
            fqdn: Fully-qualified domain name.
            flags: Key flags — 257 (KSK, default) or 256 (ZSK).
        """
        try:
            assert_readwrite(ctx, "create LiveDNS DNSSEC key")
            return await get_client(ctx).livedns_create_key(fqdn, flags=flags)
        except Exception as e:
            handle_client_error(e)

    @mcp.tool(
        tags={"gandi", "livedns", "write"},
        annotations={"readOnlyHint": False, "destructiveHint": True},
    )
    async def livedns_delete_dnssec_key(ctx: Context, fqdn: str, key_id: str) -> dict[str, Any]:
        """Delete a LiveDNS DNSSEC key.

        Args:
            fqdn: Fully-qualified domain name.
            key_id: ID of the DNSSEC key to delete.
        """
        try:
            assert_readwrite(ctx, "delete LiveDNS DNSSEC key")
            return await get_client(ctx).livedns_delete_key(fqdn, key_id)
        except Exception as e:
            handle_client_error(e)
